# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59c09bf040e0833a158ff55bc443d4aab783476d28ddb2d6d6d4b2297a159829458410712bbc7700e0daebc469fd34296f1fea4da69eb147a48eda84bf1cb01f

test:
  secret_key_base: 0160c93606a9428b3866429bbf08bca6749f45fab958b094d2253d4b693c0c2a83f70ce702e95d3d328e9cc50e6a3138191fe3fbd7d3d38ca70b935dae537d31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
